DROP DATABASE IF EXISTS MOVIE_DB;

CREATE DATABASE MOVIE_DB;

\C MOVIE_DB;

CREATE TABLE MOVIES (
    ID SERIAL PRIMARY KEY,
    MOVIE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE REVIEWS (
    ID SERIAL PRIMARY KEY,
    MOVIE_ID INTEGER NOT NULL,
    REVIEWS TEXT,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(ID) ON DELETE SET NULL
);