DROP DATABASE IF EXISTS Employee_DB;

CREATE DATABASE Employee_DB;

\C Employee_DB;

CREATE TABLE DEPARTMENT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(30) UNIQUE NOT NULL,
);

CREATE TABLE ROLE ( -- might have to rename - role is a reserved word--
    ID SERIAL PRIMARY KEY,
    title VARCHAR(30) UNIQUE NOT NULL, 
    SALARY DECIMAL NOT NULL,
    DEPARTMENT_ID INTEGER NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID )
    REFERENCES DEPARTMENT(ID)
    ON DELETE SET NULL

) 

CREATE TABLE ROLE (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL
    last_name VARCHAR(30) NOT NULL
    role_id INTEGER NOT NULL
    manager_id INTEGER not NULL
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLE(ID)
    FOREIGN KEY (manager_id)
    REFERENCES employee(id)
    
);

// check