DROP DATABASE IF EXISTS EMPLOYEE_DB;

CREATE DATABASE EMPLOYEE_DB;

\C EMPLOYEE_DB;

CREATE TABLE DEPARTMENT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE ROLE (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(30) UNIQUE NOT NULL,
    SALARY DECIMAL NOT NULL,
    DEPARTMENT_ID INTEGER NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID) ON DELETE SET NULL
);

CREATE TABLE EMPLOYEE (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    MANAGER_ID INTEGER NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE SET NULL,
    REFERENCES EMPLOYEE ON DELETE SET NULL
);